name: spring-metrics

services:
  prometheus:
    image: prom/prometheus:main
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise:main
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
