spring:
  application:
    name: spring-metrics

server:
  port: 8080

management:
  metrics:
    tags:
      namespace: local
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
