{
 "title": "Spring Boot Executors",
 "description": "Spring Boot (Micrometer) with Executors.",
 "tags": [
  "prometheus",
  "spring-boot",
  "micrometer",
  "executor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(executor_active_threads, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(executor_active_threads{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(executor_active_threads{namespace=\"$namespace\", application=\"$application\"}, instance)"
    }
   },
   {
    "name": "executor_name",
    "label": "Executor",
    "query": {
     "query": "label_values(executor_active_threads{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active threads",
   "type": "timeseries",
   "description": "The approximate number of threads that are actively executing tasks.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_active_threads{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by (namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Current pool",
   "type": "timeseries",
   "description": "The current number of threads in the pool.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_pool_size_threads{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by(namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Core pool",
   "type": "timeseries",
   "description": "The core number of threads for the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_pool_core_threads{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by(namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max pool size",
   "type": "timeseries",
   "description": "The maximum allowed number of threads in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_pool_max_threads{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by(namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Queued tasks",
   "type": "timeseries",
   "description": "The approximate number of tasks that are queued for execution.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_queued_tasks{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by(namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Completed tasks",
   "type": "timeseries",
   "description": "The approximate total number of tasks that have completed execution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(executor_completed_tasks_total{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}[$__rate_interval])) by(namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining tasks",
   "type": "timeseries",
   "description": "The number of additional elements that this queue can ideally accept without blocking.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_queue_remaining_tasks{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by(namespace, application, name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}