{
 "title": "spring-metrics",
 "description": "Dashboard of spring-metric - Spring Boot Application.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(application_started_time_seconds,namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(application_started_time_seconds{namespace=\"$namespace\"},application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Article operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of created articles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "increase(spring_metrics_article_creating_objects_total{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) != 0",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Number of received articles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "increase(spring_metrics_article_receiving_objects_total{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) != 0",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Number of updated articles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "increase(spring_metrics_article_updating_objects_total{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) != 0",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Number of deleted articles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "increase(spring_metrics_article_deleting_objects_total{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) != 0",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Daily article creating",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time of creating daily articles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(spring_metrics_article_creating_daily_seconds_sum{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) / rate(spring_metrics_article_creating_daily_seconds_count{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval])",
       "legendFormat": "Time"
      }
     ]
    },
    {
     "title": "Number of daily articles not created",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "increase(spring_metrics_article_creating_daily_empty_objects_total{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) != 0",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Number of nested articles in a daily article",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "increase(spring_metrics_article_creating_daily_nested_objects_total{namespace=\"$namespace\", application=\"$application\"}[$__rate_interval]) != 0",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  }
 ]
}